### ISSUE TITLE
error in creating pod of client

### ISSUE THREAD

**Issue by yeganx** [davsclaus/fabric8-hello#2]
hi 
I have problem in running client2 on kubernets 
the log of this pod is 
Log for client-1004295647-yjpwg / spring-boot

exec java -javaagent:/opt/agent-bond/agent-bond.jar=jolokia{{host=0.0.0.0}},jmx_exporter{{9779:/opt/agent-bond/jmx_exporter_config.yml}} -cp . -jar /deployments/client-1.0-SNAPSHOT.jar

I> No access restrictor found, access to any MBean is allowed

Jolokia: Agent started with URL http://172.17.0.6:8778/jolokia/

2016-10-18 14:55:11.359:INFO:ifasjipjsoejs.Server:jetty-8.y.z-SNAPSHOT

2016-10-18 14:55:11.403:INFO:ifasjipjsoejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:9779

Exception in thread "main" java.lang.IndexOutOfBoundsException

at org.springframework.boot.loader.jar.AsciiBytes.(AsciiBytes.java:68)

at org.springframework.boot.loader.jar.CentralDirectoryFileHeader.load(CentralDirectoryFileHeader.java:83)

at org.springframework.boot.loader.jar.CentralDirectoryParser.parseEntries(CentralDirectoryParser.java:68)

at org.springframework.boot.loader.jar.CentralDirectoryParser.parse(CentralDirectoryParser.java:57)

at org.springframework.boot.loader.jar.JarFile.(JarFile.java:118)

at org.springframework.boot.loader.jar.JarFile.(JarFile.java:106)

at org.springframework.boot.loader.jar.JarFile.createJarFileFromFileEntry(JarFile.java:290)

at org.springframework.boot.loader.jar.JarFile.createJarFileFromEntry(JarFile.java:260)

at org.springframework.boot.loader.jar.JarFile.getNestedJarFile(JarFile.java:248)

at org.springframework.boot.loader.jar.JarFile.getNestedJarFile(JarFile.java:237)

at org.springframework.boot.loader.archive.JarFileArchive.getNestedArchive(JarFileArchive.java:103)

at org.springframework.boot.loader.archive.JarFileArchive.getNestedArchives(JarFileArchive.java:87)

at org.springframework.boot.loader.ExecutableArchiveLauncher.getClassPathArchives(ExecutableArchiveLauncher.java:72)

at org.springframework.boot.loader.Launcher.launch(Launcher.java:49)

at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:58
## and in events tab

Error syncing pod, skipping: failed to "StartContainer" for "spring-boot" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=spring-boot pod=client-1004295647-yjpwg_default(2b2f8ff6-953f-11e6-bae1-1a074b26354e)" 
what is the problem ?
tnx in advance

**Comment by davsclaus** [comment]
Sorry for the delay? Which client2 do you refer to? Is it client or client-hystrix?
